name: CodeCompileTest
on: 
  push:
    branches:    
      - main
      - RELEASES/**
      - users/**
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
      with:
        node-version: '14'
    - name: change directory
      run: |
        cd perfanalyzer
    - name: npm install
      run: |
        cd perfanalyzer
        npm install
        cd src
        rm appInsightsConnectionString-ms.ts
        rm appInsightsConnectionString.ts
        touch appInsightsConnectionString-ms.ts
        touch appInsightsConnectionString.ts
        echo "export const APPINSIGHTS_CONNECTION_MS_CLASSIC_STRING='${{ secrets.APPINSIGHTS_CONNECTION_MS_CLASSIC_TEST_STRING }}'" 
        echo "export const APPINSIGHTS_CONNECTION_STRING='${{ secrets.APPINSIGHTS_CONNECTION_TEST_STRING }}'"
        echo "export const APPINSIGHTS_CONNECTION_MS_CLASSIC_STRING='${{ secrets.APPINSIGHTS_CONNECTION_MS_CLASSIC_TEST_STRING }}'" >>  appInsightsConnectionString-ms.ts
        echo "export const APPINSIGHTS_CONNECTION_STRING='${{ secrets.APPINSIGHTS_CONNECTION_TEST_STRING }}'" >>  appInsightsConnectionString.ts
        cd ..
        tsc index.ts